config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'new', to: 'games#new'
  post 'score', to: 'games#score'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'json'
require 'open-uri'

class GamesController < ApplicationController

  def new
   @letters = [*('A'..'Z')].sample(10)
  end

def score
    word = params[:word].chars #["A", "B", "B"]
    grid = params[:grid].chars #["A", "B", "C"]
    results = word.all? {|letter| word.count(letter) <= grid.count(letter)}
    if results
      url = "https://wagon-dictionary.herokuapp.com/#{params[:word]}"
      user_serialized = URI.open(url).read
      user = JSON.parse(user_serialized)
      if user["found"]
        @answer = "Well done"
      else
        @answer = "Not english word"
      end
    else
      @answer = "This word is not matching"
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<ul>
  <% @letters.each do |letter| %>
    <li><%= letter %></li>
  <% end %>
</ul>
<p>What is the longest word you can find ?</p>

<form action="/score" method="POST">
  <input type="text" name="word">
  <input type="text" name="grid" hidden="true" value="<%= @letters.join(',') %>">
  <input type="submit" value="New!">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
</form>


<%= link_to'play again', score_path %>

app/views/games/score.html.erb
<%= @answer %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>